Extension { #name : #Object }

{ #category : #'*GToolkit-Roadmaps' }
Object >> isTMFieldNode [
	^ false
]

{ #category : #'*GToolkit-Roadmaps' }
Object >> isTMNodeGroup [
	^ false
]

{ #category : #'*GToolkit-Roadmaps' }
Object >> isTMPageGroup [
	^ false
]

{ #category : #'*GToolkit-Roadmaps' }
Object >> isTMPageNode [
	^ false
]

{ #category : #'*GToolkit-Roadmaps' }
Object >> isTMTreeNode [
	^ false
]
